### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by QYueWang** [cdeadlock/doc88-download-userscript#1]
I do know how to use it

**Comment by cdeadlock** [comment]
Use a program like TamperMonkey for Chrome. 
It runs "user scripts" (client side javascript to do anything you want to a website)

Read the description in the code:
It creates a button on the top right of the page called "load", click it, it will automatically scroll through the document to make sure it is all loaded, it hides some advertising and other useless things, so you can then print the document to PDF.
